name: Call default true

on:
  workflow_call:
    inputs:
      f:
        required: false
        default: true
        type: boolean
  workflow_dispatch:
    inputs:
      f:
        required: false
        default: true
        type: boolean

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.inputs.f }}

  run-if-true:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.f }}
    steps:
      - run: echo run-if-true

  run-if-false:
    runs-on: ubuntu-latest
    if: ${{ !github.event.inputs.f }}
    steps:
      - run: echo run-if-false

  run-if-str-true:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.f == 'true' }}
    steps:
      - run: echo run-if-str-true

  run-if-str-false:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.f == 'false' }}
    steps:
      - run: echo run-if-str-false
